from fastapi import APIRouter, HTTPException
from database import supabase
from models import Work

router = APIRouter()

@router.post("/", response_model=Work)
def create_work(work: Work):
    # Exclude id if it's generated by DB, but here we might want to let DB handle it or client.
    # The model has 'id', let's assume client sends it or we generate it.
    # Actually, usually DB generates ID. Let's make ID optional in creation?
    # For now, let's assume the client sends the ID (as per frontend logic using Date.now()) 
    # OR we change frontend to let backend handle it.
    # Better: Let backend/DB handle ID. But frontend currently generates it.
    # Let's try to insert what we get.
    
    work_data = work.model_dump(by_alias=True, exclude_none=True)
    response = supabase.table("works").insert(work_data).execute()
    if not response.data:
        raise HTTPException(status_code=500, detail="Failed to create work")
    return response.data[0]

@router.put("/{id}", response_model=Work)
def update_work(id: str, work: Work):
    work_data = work.model_dump(by_alias=True, exclude={"id", "created_at", "composer_id"}, exclude_none=True)
    response = supabase.table("works").update(work_data).eq("id", id).execute()
    if not response.data:
        raise HTTPException(status_code=404, detail="Work not found")
    return response.data[0]

@router.delete("/{id}")
def delete_work(id: str):
    response = supabase.table("works").delete().eq("id", id).execute()
    if not response.data:
        raise HTTPException(status_code=404, detail="Work not found")
    return {"message": "Work deleted successfully"}
